{{ if lookPath "tmux" }}
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}
